### ISSUE TITLE
Bug of traduction

### ISSUE THREAD

**Issue by Mrsvaca** [null3000/StarWarsWeatherExtension#1]
Hello, I saw a bug of the traduction that sais (Is a cool afertnoon)(ENG) (Es una Tarde frio Tarde)(ESP) that means in english its a afertnoon cold afertenon

**Comment by null3000** [comment]
Hello, thank you for bringing this to my attention. I have fixed it in v1.3.2. I have submitted it to the chrome web store, and it should be available within the next few days.
