### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by tiagoledess** [null3000/StarWarsWeatherExtension#3]
Hi!
I have a translation issue with the weather in the menu. It says (in spanish because i speak spanish) "Es un Evening LLuvioso" which means "Its a rainy evening" but the word "Evening" its not being translated at all. It should say "Es un atardecer lluvioso".
Its just a minor error but i hope you fix it.
Thanks!

**Comment by null3000** [comment]
Ok, I will look into this and fix it for the next patch. Thank you for bringing this to my attention.
