### ISSUE TITLE
readability issue

### ISSUE THREAD

**Issue by Cesarello** [null3000/StarWarsWeatherExtension#5]
Hello, I love the extension but some of the white text kinda disappears on the background art (for example in the clouds of the Naboo image). It would be helpful to have a little black border around the letters, or semi-transparent dark layer to increase the contrast between the text and the background

Thank you!

<img width="1827" alt="Screenshot 2024-04-18 alle 08 43 30" src="https://github.com/null3000/StarWarsWeatherExtension/assets/80453474/2f4d8d8f-40e0-4566-9b19-206870986355">

**Comment by null3000** [comment]
Will be fixed in next update, thank you.
